### ISSUE TITLE
Possible Typo in example uvc-ndsi-bridge-host.py

### ISSUE THREAD

**Issue by koamd** [pupil-labs/pyndsi#49]
While I was running uvc-ndsi-bridge-host.py

The following error was produced:

```
C:MyWorkspace\pyndsi\examples>python uvc-ndsi-bridge-host.py
Traceback (most recent call last):
  File "uvc-ndsi-bridge-host.py", line 210, in <module>
    Bridge(uuid).loop()
  File "uvc-ndsi-bridge-host.py", line 39, in init
    self.cap = uvc.Capture(uvc_id)
  File "uvc.pyx", line 455, in uvc.Capture.init
  File "uvc.pyx", line 507, in uvc.Capture._init_device
uvc.OpenError
Exception ignored in: <bound method Bridge.del of <main.Bridge object at 0x000001D542FAD0B8>>
Traceback (most recent call last):
  File "uvc-ndsi-bridge-host.py", line 115, in del
    self.note.close()
AttributeError: 'Bridge' object has no attribute 'note'
```

Though this is also partially due to me not connecting the camera via UVC.

**Comment by papr** [comment]
Apologies for the very late response. Looking at this again, this is not a bug.

The exception happens during `Bridge.__init__` which calls [`Bridge.__del__`](https://github.com/pupil-labs/pyndsi/blob/master/examples/uvc-ndsi-bridge-host.py#L133-L137) to clean up the object. At that time. `self.note` is not properly initialised yet. But all exceptions in `__del__` are ignored

> Exception ignored in: `<bound method Bridge.del ...`

So this is not actually an issue.

The initial exception happens because pyuvc fails to open the the camera with the corresponding `uvc_id` value.
